export const greetings = [
    'Den uundersøgte liv er ikke værd at leve. — Sokrates (ca. 399 f.Kr.)',
    'Vi lider oftere i fantasien end i virkeligheden. — Seneca (ca. 65 e.Kr.)',
    'Lykke afhænger af os selv. — Aristoteles (ca. 340 f.Kr.)',
    'Det er ikke døden, man skal frygte, men aldrig at begynde at leve. — Marcus Aurelius (ca. 170 e.Kr.)',
    'Ingen mand træder ud i den samme flod to gange, for det er ikke den samme flod, og han er ikke den samme mand. — Heraklit (ca. 500 f.Kr.)',
    'Det er i vores stilhed, vi finder os selv. — Epiktet (ca. 100 e.Kr.)',
    'Mål ikke en mand på hans medgang, men på hvordan han rejser sig efter fald. — Konfucius (ca. 500 f.Kr.)',
    'At turde er at miste fodfæstet for en stund. Ikke at turde er at miste sig selv. — Søren Kierkegaard (1849)',
    'Livet kan kun forstås baglæns, men det må leves forlæns. — Søren Kierkegaard (1843)',
    'Man skal tvivle om alt – men ikke fortvivle over alt. — René Descartes (1637)',
    'Hav mod til at bruge din egen forstand. — Immanuel Kant (1784)',
    'Den der har et hvorfor at leve for, kan bære næsten ethvert hvordan. — Friedrich Nietzsche (1889)',
    'Man må forestille sig Sisyfos lykkelig. — Albert Camus (1942)',
    'Ensomhed er fattigdom for den, der ikke har sig selv. — Arthur Schopenhauer (ca. 1850)',
    'Den eneste sande visdom er at vide, at man intet ved. — Sokrates, gengivet af Platon (ca. 399 f.Kr.)',
    'Bliv den du er. — Friedrich Nietzsche (1882)',
    'Stilhed er en kilde til stor styrke. — Lao Tzu (ca. 600 f.Kr.)',
    'Frihed er hvad du gør med det, der er gjort mod dig. — Jean-Paul Sartre (1946)',
    'Det er aldrig for sent at blive den, man kunne have været. — tilskrevet George Eliot (ca. 1860)',
    'Livet er det, der sker, mens du laver andre planer. — Allen Saunders (1957)',
    'Den største sejr er den, der ikke kræver kamp. — Sun Tzu (ca. 500 f.Kr.)',
    'Verden er fuld af magiske ting, der tålmodigt venter på, at vores sanser bliver skarpere. — W.B. Yeats (ca. 1920)',
    'Vi er hvad vi gentagne gange gør. Fortræffelighed er altså ikke en handling, men en vane. — Will Durant om Aristoteles (1926)',
    'Mellem stimulus og respons er der et rum. I det rum ligger vores frihed. — Viktor Frankl (1946)',
    'Enkelthed er den ultimative sofistikering. — tilskrevet Leonardo da Vinci (ca. 1500)',
    'Rejsen på tusind mil begynder med et enkelt skridt. — Lao Tzu (ca. 600 f.Kr.)',
    'Når eleven er klar, viser læreren sig. — buddhistisk ordsprog',
    'Det er bedre at tænde et lys end at forbande mørket. — kinesisk ordsprog',
    'Den bedste tid at plante et træ var for tyve år siden. Den næstbedste tid er nu. — kinesisk ordsprog',
    'Det blæser ikke altid storm; selv havet hviler. — Epikur (ca. 300 f.Kr.)',
    'Det er i ufuldkommenheden, skønheden bor. — wabi-sabi, japansk æstetik (ca. 1400-tallet)'
]
