export const models = [
    { value: 'icon_seamless', label: 'DWD ICON', group: 'Seamless' },
    { value: 'gfs_seamless', label: 'GFS', group: 'Seamless' },
    { value: 'meteofrance_seamless', label: 'Météo-France', group: 'Seamless' },
    { value: 'gem_seamless', label: 'GEM', group: 'Seamless' },
    { value: 'jma_seamless', label: 'JMA', group: 'Seamless' },
    { value: 'kma_seamless', label: 'KMA', group: 'Seamless' },
    { value: 'dmi_seamless', label: 'DMI', group: 'Seamless' },
    { value: 'knmi_seamless', label: 'KNMI', group: 'Seamless' },
    { value: 'ukmo_seamless', label: 'UKMO', group: 'Seamless' },
    { value: 'ecmwf_ifs025', label: 'ECMWF IFS 0.25°', group: 'Europa' },
    { value: 'ecmwf_ifs04', label: 'ECMWF IFS 0.4°', group: 'Europa' },
    { value: 'ecmwf_aifs025', label: 'ECMWF AIFS (AI)', group: 'Europa' },
    { value: 'dwd_icon_global', label: 'DWD ICON Global', group: 'Europa' },
    { value: 'dwd_icon_eu', label: 'DWD ICON EU', group: 'Europa' },
    { value: 'dwd_icon_d2', label: 'DWD ICON D2', group: 'Europa' },
    { value: 'meteofrance_arpege_world', label: 'Arpège World', group: 'Europa' },
    { value: 'meteofrance_arpege_europe', label: 'Arpège Europe', group: 'Europa' },
    { value: 'knmi_harmonie_arome_europe', label: 'KNMI Harmonie EU', group: 'Europa' },
    { value: 'dmi_harmonie_arome_europe', label: 'DMI Harmonie EU', group: 'Europa' },
    { value: 'ncep_gfs_global', label: 'GFS Global', group: 'Nordamerika' },
    { value: 'gem_global', label: 'GEM Global', group: 'Nordamerika' },
    { value: 'jma_gsm', label: 'JMA GSM', group: 'Asien/Oceanien' },
    { value: 'kma_gdps', label: 'KMA GDPS', group: 'Asien/Oceanien' },
    { value: 'cma_grapes_global', label: 'CMA GRAPES', group: 'Asien/Oceanien' },
    { value: 'bom_access_global', label: 'BOM ACCESS', group: 'Asien/Oceanien' }
]
